server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : ${jasypt.encryptor.password}

fixed-extension:
  list: bat,cmd,com,cpl,exe,scr,js

max-extension-count: 200
---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XNt/92kYzCs/ffDwg2ipzb9vlIPV6LKx9Gp/7k9Vg7siPiaPtOVslmeM6BeOfWCTeACMWfyEmeFnKfLl9A2EhR6UkJogpwmmsDczpHnpqzsTGZauIIaQgg==)
    username: ENC(JSA0hNARMgm0qYpD/4Iraw==)
    password: ENC(41s1mrhbplL/ZmzU0El5mw==)
---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(J5RKt56vEHCDTcfVPQ1dc9+grEA8x8hJi96zWJ29rJhH0SLA9NxTLDjm1+gFr1tVRaLSk9xSS+9vYG2LL0XVWwUisC3ODQv9/CKxEri+YNCt9F0TF4vXDp7xzZ8ZxDAgGKA0MB3rXqM=)
    username: ENC(+KIeOYhUigocEDHw8g6cEw==)
    password: ENC(DMAhmrMeRAvG5ZNg2ofuQA==)
